//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMTEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMTEditor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;CPedVariationInfo&gt;
        ///  &lt;bHasTexVariations value=&quot;true&quot; /&gt;
        ///  &lt;bHasDrawblVariations value=&quot;true&quot; /&gt;
        ///  &lt;bHasLowLODs value=&quot;true&quot; /&gt;
        ///  &lt;bIsSuperLOD value=&quot;false&quot; /&gt;
        ///  &lt;availComp&gt;255 255 255 255 255 255 255 255 255 255 255 255&lt;/availComp&gt;
        ///  &lt;aComponentData3 itemType=&quot;CPVComponentData&quot;/&gt;
        ///  &lt;aSelectionSets itemType=&quot;CPedSelectionSet&quot; /&gt;
        ///  &lt;compInfos itemType=&quot;CComponentInfo&quot;/&gt;
        ///  &lt;propInfo&gt;
        ///    &lt;numAvailProps value=&quot;0&quot; /&gt;
        ///    &lt;aPropMetaData itemType=&quot;CPedPropMetaDat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_ymt {
            get {
                return ResourceManager.GetString("template_ymt", resourceCulture);
            }
        }
    }
}
